version: '3.4'

services:
    postgresql_database:
        container_name: postgresql
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin1234
            PGDATA: /data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - postgres
            - facenet

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin1234
        ports:
            - '5050:80'
        restart: unless-stopped
        networks:
            - postgres
            - facenet
        volumes:
            - pgadmin:/var/lib/pgadmin

    front:
        build: ./faceweb
        container_name: front
        ports:
           - "5000:5000"
        command: python3 -m flask run --host 0.0.0.0

    back:
        build: ./server
        container_name: back
        ports:
            - 8821:8821
        command: python3 server.py
        depends_on:
            - postgresql_database
            - front
            - pgadmin
        networks:
            - facenet

volumes:
    database-data:
    pgadmin:

networks:
    postgres:
    facenet:
